name: PR_unit_tests

on:
  pull_request:
    branches:
    - 'main'

jobs:
  Unit-test:
    name: Run unit tests on PR in main
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '8'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: get all files mode
        run: ls -al
      - name: Change gradle wrapper permission
        run: chmod +x gradlew
      - name: Run unit tests
        run: ./gradlew test