name: PR_unit_tests

on:
  pull_request:
    branches:
    - 'main'

jobs:
  Unit-test:
    name: Run unit tests on PR in main
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with: {java-version: 1.8}
      - name: get all files mode
        run: ls -al
      - name: Change gradle wrapper permission
        run: chmod +x gradlew
      - name: Run unit tests
        run: ./gradlew test