name: PR_unit_tests

on:
  pull_request:
    branches:
    - 'main'

jobs:
  Unit-test:
    name: Run unit tests on PR in main
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: get all files mode
        run: cd app && ls -al
      - name: Change gradle wrapper permission
        run: chmod +x gradlew
      - name: Run unit tests
        run: ./gradlew test